# Generated by Django 6.0.6 on 2026-06-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='student_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
