# Generated by Django 6.0.7 on 2026-07-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Order Inquiry', 'Order Inquiry'), ('Returns & Exchanges', 'Returns & Exchanges'), ('Product Question', 'Product Question'), ('Wholesale / Partnership', 'Wholesale / Partnership'), ('Feedback', 'Feedback'), ('Something Else', 'Something Else')], default='Something Else', max_length=40)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
